version: '3'

services:
  zk1:
    # 镜像
    image: zookeeper:3.6.2
    restart: always
    # 端口映射
    ports:
      - "12181:2181"
    # 环境变量
    environment:
      # 当前zk实例的id
      ZOO_MY_ID: 1
      # 整个zk集群的机器、端口列表
      # 改动每个点ip和端口发生改变
      ZOO_SERVERS: server.1=0.0.0.0:12888:13888;2181 server.2=zk2:12888:13888;2181 server.3=zk3:12888:13888;2181
    # 网络
    networks:
      - zk-net
    # 数据券
    volumes:
      - ./data/zk1:/data
      - ./logs/zk1:/datalog
  zk2:
    image: zookeeper:3.6.2
    restart: always
    ports:
      - "22181:2181"
    environment:
      ZOO_MY_ID: 2
      # 改动每个点ip和端口发生改变
      ZOO_SERVERS: server.1=zk1:12888:13888;2181 server.2=0.0.0.0:12888:13888;2181 server.3=zk3:12888:13888;2181
    networks:
      - zk-net
    volumes:
      - ./data/zk2:/data
      - ./logs/zk2:/datalog

  zk3:
    image: zookeeper:3.6.2
    restart: always
    ports:
      - "32181:2181"
    environment:
      ZOO_MY_ID: 3
      # 改动每个点ip和端口发生改变
      ZOO_SERVERS: server.1=zk1:12888:13888;2181 server.2=zk2:12888:13888;2181 server.3=0.0.0.0:12888:13888;2181
    networks:
      - zk-net
    volumes:
      - ./data/zk3:/data
      - ./logs/zk3:/datalog

  kafka1:
    image: confluentinc/cp-kafka:latest
    restart: always
    depends_on:
      - zk1
      - zk2
      - zk3
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2181,zk3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./data/kafka1:/var/lib/kafka/data # 数据持久化
    networks:
      - zk-net
  kafka2:
    image: confluentinc/cp-kafka:latest
    restart: always
    depends_on:
      - zk1
      - zk2
      - zk3
    ports:
      - 29093:29093
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2181,zk3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092,PLAINTEXT_HOST://localhost:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./data/kafka2:/var/lib/kafka/data # 数据持久化
    networks:
      - zk-net
  kafka3:
    image: confluentinc/cp-kafka:latest
    restart: always
    depends_on:
      - zk1
      - zk2
      - zk3
    ports:
      - 29094:29094
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2181,zk3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092,PLAINTEXT_HOST://localhost:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./data/kafka3:/var/lib/kafka/data # 数据持久化
    networks:
      - zk-net
# 给zk集群配置一个网络，网络名为zk-net，模式为bridge
networks:
  zk-net:
    driver: bridge
# docker exec -ti [zookeeper容器id] zkServer.sh status  查看状态